### ISSUE TITLE
Error in defhydra ivy-read-action: (Key sequence s g starts with non-prefix key s)

### ISSUE THREAD

**Issue by cocreature** [ericdanan/counsel-projectile#67] opened 2018-01-03 16:44 UTC
When I press `C-c p p` to launch `counsel-projectile-switch-project` followed by `M-o` to select the action I’m presented with the error message in the issue title:

```
Error in defhydra ivy-read-action: (Key sequence s g starts with non-prefix key s) 
```

This is a regression that has been introduced in 2fc8dca25713d110fe3882c111f4f2509e5d52d3. I’m using `counsel-0.10.0` and `ivy-0.10.0`. (I don’t have time to test the master branches of those right now).

**Comment by ericdanan** [comment] 2018-01-04 11:01
Thanks, I can reproduce the issue.

It arises because `counsel-projectile-switch-project` has actions with multi-character keys (such as the `sg` action to search project with grep). Since such keys are not supported by ivy, I implemented a workaround in counsel-projectile consisting in adding "prefix" actions (such as the `s` action to further select between the various project search actions). But it turns out that this workaround is incompatible with ivy-hydra.

I just sent a PR to support these multi-character keys in ivy, see abo-abo/swiper/pull/1394. If it is merged then the "prefix" actions won't be needed anymore and everything will work with or without ivy-hydra. If it is not merged then I will have to think of another workaround.

**Comment by paulbdavis** [comment] 2018-01-04 18:02
Same issue here (and now `M-o g` is in my muscle memory for getting to magit)

Is there a way to rebind `M-o` easily when using `counsel-projectile-switch-project`?

**Comment by ericdanan** [comment] 2018-01-04 20:29
I know the keybinding change can be annoying, sorry about that, but it seemed to me that it would become unavoidable at some point as more and more actions are added to `counsel-projectile-switch-project`. So I decided to do it now, and to mirror the keybindings from `projectile-command-map` which are not likely to change in the future I think. This led me to implement these multi-character keys, which led to the current issue with ivy-hydra, unfortunately.

Let's see what happens with the PR I sent to ivy. In the meantime, if you have ivy-hydra loaded, a workaround is to remove the two prefix actions of `counsel-projectile-switch-project` (`s` and `x`). You can do that easily by evaluating this:

```emacs-lisp
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((remove "s")
   (remove "x")))
```

If you also want to change the `v` key to `g`, then you can evaluate this instead:

```emacs-lisp
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((remove "s")
   (remove "x")
   (setkey "v" "g")))
```

You can also make other modifications to action lists with the command `counsel-projectile-modify-action`, see its docstring for details.

**Comment by paulbdavis** [comment] 2018-01-05 01:19
Thanks for the response. This should work well in case that PR never makes it in.

**Comment by ericdanan** [comment] 2018-01-05 08:50
The PR was merged, so I could get rid of these prefix actions. Please update ivy and counsel-projectile, everything should now work without needing to customize anything.

**Closed as completed by ericdanan** 2018-01-05 08:50 UTC
