### ISSUE TITLE
How to pass arguments to ag (searching for files in a hidden dir)

### ISSUE THREAD

**Issue by nayefc** [ericdanan/counsel-projectile#20] opened 2016-12-06 21:17 UTC
How can I pass arguments to `counsel-projectile-ag`? I'd like to search for files that are contained inside a hidden directory in my project.

Thanks.

**Comment by ericdanan** [comment] 2016-12-07 10:07
You can pass the arguments as a string:

```
(counsel-projectile-ag ARGS)
```

will invoke (with the default value of `counsel-ag-base-command`)

```
ag --nocolor --nogroup ARGS
```

If you call `counsel-projectile-ag` with a `C-u` prefix, then the ARGS strings will be read from the minibuffer.

**Comment by ericdanan** [comment] 2016-12-12 09:51
I just realized it was probably not working because `counsel-projectile-ag` was not formatting the arguments correctly (a space was missing).

Should be fixed now. Could you test and let me know if it works for you?

Thanks.

**Comment by tlegutko** [comment] 2017-05-04 01:26
I'm a bit late to the party, but I had the exact same use-case and I can confirm that @ericdanan solution with `C-u` (`--hidden` option in this case) prefix works perfectly, so I guess the issue can be closed now :).

**Comment by ericdanan** [comment] 2017-08-15 14:27
Thanks, I am closing this issue then.

**Closed as completed by ericdanan** 2017-08-15 14:27 UTC
