### ISSUE TITLE
Issue in terminal using arrow keys in the counsel-projectile mini-buffer

### ISSUE THREAD

**Issue by valerian** [ericdanan/counsel-projectile#115] opened 2018-12-05 11:41 UTC
I'm not sure if this is the problem comes from counsel-projectile, but it seems likely.

I'm currently using Emacs within xterm:
- When I'm in counsel-projectile mini-buffer and keep arrow down or arrow up pressed, I keep getting the following error: `ESC <down> is undefined` or `ESC <up> is undefined`.
- Quickly pressing the up and down arrow keys in succession does not generate this error, only keeping them pressed down does.
- Lowering the keyboard repeat rate does fix the issue, but it requires to set it way too slow.
- I do not have this issue in any other counsel mini-buffers, or in anywhere else in Emacs and various packages.

I would appreciate some help with that!

I temporarily fixed it locally by doing:
```
(define-key key-translation-map (kbd "ESC <down>") (kbd "<down>"))
(define-key key-translation-map (kbd "ESC <up>") (kbd "<up>"))
```

**Comment by ericdanan** [comment] 2018-12-05 14:41
I have no idea why `counsel-projectile` would have anything particular with respect to holding the up or down arrow key. I don't use emacs from terminal, just tried in bash (I don't have xterm) and couldn't reproduce the issue.

Do you have the same issue with `counsel-projectile-find-file` or `counsel-projectile-switch-to-buffer`? And is so, what about `projectile-find-file` and `projectile-switch-to-buffer`?

**Comment by valerian** [comment] 2018-12-06 09:45
I have no issue with either `counsel-projectile-find-file`, `counsel-projectile-switch-to-buffer`, `projectile-find-file`, or `projectile-switch-to-buffer`

The issue is really only with the `counsel-projectile` command, I never had any issue looking like this one in any other command.

**Update:**

After some testing I realized that removing this line from my .emacs solved this issue:
`(icomplete-mode 1)`

Well, I guess I don't need icomplete-mode anymore with ivy and counsel anyway, I used to have it enabled by default since so many years I forgot it was there ...

**Comment by ericdanan** [comment] 2018-12-06 15:02
I tried once again in bash and turning on icomplete mode but still couldn't reproduce your issue.

Anyway, I guess it doesn't really make sense to use icomplete and ivy at the same time and one can expect conflicts if doing so. I have no clue why it only happens with the `counsel-projectile` command though.

**Comment by ericdanan** [comment] 2019-01-08 08:47
Closing, please reopen if needed.

**Closed as completed** 2019-01-08 08:47 UTC
