### ISSUE TITLE
counsel-projectile-switch-to-buffer is surprisingly slow

### ISSUE THREAD

**Issue by matthewlmcclure** [ericdanan/counsel-projectile#16] opened 2016-10-31 19:21 UTC
When I do `C-c p b`, Emacs takes a long time -- tens of seconds or a small minutes -- to return.

**Comment by ericdanan** [comment] 2016-10-31 20:53
I can't reproduce this, could you elaborate a bit more? Is `counsel-projectile-switch-to-buffer` slower then `projectile-switch-to-buffer`? If you call `counsel-projectile-switch-to-buffer` several times in a row, is it always slow? What f you start a fresh emacs session and just have a couple of project buffers open?

**Comment by matthewlmcclure** [comment] 2016-11-01 00:37
projectile-switch-to-buffer seems much faster.

Repeating counsel-projectile-switch-to-buffer doesn't seem to make it any
faster than the first time.

I quit Emacs and restarted. On restart, it indicated that counsel was
required by counsel-projectile, but the former was not installed. I
installed counsel and restarted Emacs again.

C-c p b is responsive now.

Thanks.

**Comment by ericdanan** [comment] 2016-11-01 11:41
OK, so is everything working for you now or are you still having an issue?

**Comment by matthewlmcclure** [comment] 2016-11-01 13:35
It seems fine now. Thanks for asking.

**Comment by ericdanan** [comment] 2016-11-01 14:25
Perfect, closing.

**Closed as completed by ericdanan** 2016-11-01 14:25 UTC
